title: Michael Knudson
description: Resume page to document Michael Knudson's experience in software engineering
author: Michael Knudon

social:
  links:
    - https://www.facebook.com/MichaelKnudson123
    - https://www.instagram.com/michael.knudson/
    - https://www.linkedin.com/in/michaelellsworthknudson/
    - https://github.com/mknudson94

plugins:
  - jekyll-seo-tag
  - jeykll-sitemap
